# Generated by Django 6.0.5 on 2026-05-24 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='author',
            field=models.CharField(choices=[('Elder.Evil', 'Elder.Evil'), ('Nyx', 'Nyx')], default='Elder.Evil', max_length=20),
        ),
    ]
