# Generated by Django 6.0.5 on 2026-05-24 15:57

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_blogpage_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2), ('embed', 3), ('code', 6)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'icon': 'title', 'template': 'blocks/heading.html'}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul', 'code']}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'template': 'blocks/image.html'}), 3: ('wagtail.embeds.blocks.EmbedBlock', (), {}), 4: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('python', 'Python'), ('javascript', 'JavaScript'), ('bash', 'Bash/Shell'), ('css', 'CSS'), ('html', 'HTML'), ('json', 'JSON'), ('yaml', 'YAML'), ('rust', 'Rust'), ('go', 'Go'), ('none', 'Plain Text')], 'required': False}), 5: ('wagtail.blocks.TextBlock', (), {}), 6: ('wagtail.blocks.StructBlock', [[('language', 4), ('code', 5)]], {'icon': 'code', 'template': 'blocks/code.html'})}),
        ),
    ]
